/**
 * Manual locative / genitive overrides for Polish city names (slug = city.id from ICity).
 * Used when heuristic declension would be wrong. Extend as you discover issues.
 * Slugs match createLinkFromText() (spacje → „-”, polskie znaki → ASCII).
 */
export type CityGrammarOverride = {
  locative: string;
  genitive: string;
};

export const CITY_GRAMMAR_OVERRIDES: Record<string, CityGrammarOverride> = {
  andrychow: { locative: "Andrychowie", genitive: "Andrychowa" },
  augustow: { locative: "Augustowie", genitive: "Augustowa" },
  belchatow: { locative: "Bełchatowie", genitive: "Bełchatowa" },
  "biala-podlaska": { locative: "Białej Podlaskiej", genitive: "Białej Podlaskiej" },
  bialapodlaska: { locative: "Białej Podlaskiej", genitive: "Białej Podlaskiej" },
  bialystok: { locative: "Białymstoku", genitive: "Białegostoku" },
  "bielsko-biala": { locative: "Bielsku-Białej", genitive: "Bielska-Białej" },
  "bielsk-podlaski": { locative: "Bielsku Podlaskim", genitive: "Bielska Podlaskiego" },
  bielskpodlaski: { locative: "Bielsku Podlaskim", genitive: "Bielska Podlaskiego" },
  bilgoraj: { locative: "Biłgoraju", genitive: "Biłgoraja" },
  bochnia: { locative: "Bochni", genitive: "Bochni" },
  boleslawiec: { locative: "Bolesławcu", genitive: "Bolesławca" },
  brzeg: { locative: "Brzegu", genitive: "Brzegu" },
  brzesko: { locative: "Brzesku", genitive: "Brzeska" },
  brodnica: { locative: "Brodnicy", genitive: "Brodnicy" },
  bydgoszcz: { locative: "Bydgoszczy", genitive: "Bydgoszczy" },
  bytom: { locative: "Bytomiu", genitive: "Bytomia" },
  chelm: { locative: "Chełmie", genitive: "Chełma" },
  chrzanow: { locative: "Chrzanowie", genitive: "Chrzanowa" },
  chorzow: { locative: "Chorzowie", genitive: "Chorzowa" },
  czestochowa: { locative: "Częstochowie", genitive: "Częstochowy" },
  ciechanow: { locative: "Ciechanowie", genitive: "Ciechanowa" },
  "dabrowa-gornicza": { locative: "Dąbrowie Górniczej", genitive: "Dąbrowy Górniczej" },
  debica: { locative: "Dębicy", genitive: "Dębicy" },
  elk: { locative: "Ełku", genitive: "Ełku" },
  elblag: { locative: "Elblągu", genitive: "Elbląga" },
  gdansk: { locative: "Gdańsku", genitive: "Gdańska" },
  gdynia: { locative: "Gdyni", genitive: "Gdyni" },
  glogow: { locative: "Głogowie", genitive: "Głogowa" },
  gliwice: { locative: "Gliwicach", genitive: "Gliwic" },
  gniezno: { locative: "Gnieźnie", genitive: "Gniezna" },
  goleniow: { locative: "Goleniowie", genitive: "Goleniowa" },
  gorlice: { locative: "Gorlicach", genitive: "Gorlic" },
  "gorzow-wielkopolski": { locative: "Gorzowie Wielkopolskim", genitive: "Gorzowa Wielkopolskiego" },
  "grodzisk-mazowiecki": { locative: "Grodzisku Mazowieckim", genitive: "Grodziska Mazowieckiego" },
  grodziskmazowiecki: { locative: "Grodzisku Mazowieckim", genitive: "Grodziska Mazowieckiego" },
  grudziadz: { locative: "Grudziądzu", genitive: "Grudziądza" },
  hajnowka: { locative: "Hajnówce", genitive: "Hajnówki" },
  ilawa: { locative: "Iławie", genitive: "Iławy" },
  inowroclaw: { locative: "Inowrocławiu", genitive: "Inowrocławia" },
  "jastrzebie-zdroj": { locative: "Jastrzębiu-Zdroju", genitive: "Jastrzębia-Zdroju" },
  jarocin: { locative: "Jarocinie", genitive: "Jarocina" },
  jaroslaw: { locative: "Jarosławiu", genitive: "Jarosławia" },
  jawor: { locative: "Jaworze", genitive: "Jawora" },
  jaworzno: { locative: "Jaworznie", genitive: "Jaworzna" },
  "jelenia-gora": { locative: "Jeleniej Górze", genitive: "Jeleniej Góry" },
  jeleniagora: { locative: "Jeleniej Górze", genitive: "Jeleniej Góry" },
  kalisz: { locative: "Kaliszu", genitive: "Kalisza" },
  katowice: { locative: "Katowicach", genitive: "Katowic" },
  "kedzierzyn-kozle": { locative: "Kędzierzynie-Koźlu", genitive: "Kędzierzyna-Koźla" },
  kielce: { locative: "Kielcach", genitive: "Kielc" },
  klodzko: { locative: "Kłodzku", genitive: "Kłodzka" },
  kluczbork: { locative: "Kluczborku", genitive: "Kluczborka" },
  kolobrzeg: { locative: "Kołobrzegu", genitive: "Kołobrzegu" },
  konin: { locative: "Koninie", genitive: "Konina" },
  koszalin: { locative: "Koszalinie", genitive: "Koszalina" },
  krosno: { locative: "Krośnie", genitive: "Krosna" },
  krotoszyn: { locative: "Krotoszynie", genitive: "Krotoszyna" },
  krakow: { locative: "Krakowie", genitive: "Krakowa" },
  krasnik: { locative: "Kraśniku", genitive: "Kraśnika" },
  kutno: { locative: "Kutnie", genitive: "Kutna" },
  legionowo: { locative: "Legionowie", genitive: "Legionowa" },
  legnica: { locative: "Legnicy", genitive: "Legnicy" },
  leszno: { locative: "Lesznie", genitive: "Leszna" },
  lezajsk: { locative: "Leżajsku", genitive: "Leżajska" },
  lodz: { locative: "Łodzi", genitive: "Łodzi" },
  lomza: { locative: "Łomży", genitive: "Łomży" },
  lowicz: { locative: "Łowiczu", genitive: "Łowicza" },
  lubin: { locative: "Lubinie", genitive: "Lubina" },
  lubon: { locative: "Luboniu", genitive: "Lubonia" },
  lublin: { locative: "Lublinie", genitive: "Lublina" },
  lukow: { locative: "Łukowie", genitive: "Łukowa" },
  mlawa: { locative: "Mławie", genitive: "Mławy" },
  mielec: { locative: "Mielcu", genitive: "Mielca" },
  myslowice: { locative: "Mysłowicach", genitive: "Mysłowic" },
  "nowy-sacz": { locative: "Nowym Sączu", genitive: "Nowego Sącza" },
  "nowy-targ": { locative: "Nowym Targu", genitive: "Nowego Targu" },
  nowytarg: { locative: "Nowym Targu", genitive: "Nowego Targu" },
  nysa: { locative: "Nysie", genitive: "Nysy" },
  olawa: { locative: "Oławie", genitive: "Oławy" },
  olesnica: { locative: "Oleśnicy", genitive: "Oleśnicy" },
  olkusz: { locative: "Olkuszu", genitive: "Olkusza" },
  olsztyn: { locative: "Olsztynie", genitive: "Olsztyna" },
  olsztynek: { locative: "Olsztynku", genitive: "Olsztynka" },
  opole: { locative: "Opolu", genitive: "Opola" },
  "ostrow-wielkopolski": { locative: "Ostrówie Wielkopolskim", genitive: "Ostrowa Wielkopolskiego" },
  ostrowwlkp: { locative: "Ostrówie Wielkopolskim", genitive: "Ostrowa Wielkopolskiego" },
  "ostrow-mazowiecka": { locative: "Ostrówie Mazowieckiej", genitive: "Ostrowi Mazowieckiej" },
  "ostrowiec-swietokrzyski": { locative: "Ostrowcu Świętokrzyskim", genitive: "Ostrowca Świętokrzyskiego" },
  ostrowiec: { locative: "Ostrowcu Świętokrzyskim", genitive: "Ostrowca Świętokrzyskiego" },
  ostroleka: { locative: "Ostrołęce", genitive: "Ostrołęki" },
  ostrod: { locative: "Ostródzie", genitive: "Ostródy" },
  oswiecim: { locative: "Oświęcimiu", genitive: "Oświęcimia" },
  otwock: { locative: "Otwocku", genitive: "Otwocka" },
  piaseczno: { locative: "Piasecznie", genitive: "Piaseczna" },
  "piekary-slaskie": { locative: "Piekarach Śląskich", genitive: "Piekier Śląskich" },
  pionki: { locative: "Pionkach", genitive: "Pionek" },
  "piotrkow-trybunalski": { locative: "Piotrkowie Trybunalskim", genitive: "Piotrkowa Trybunalskiego" },
  piotrkow: { locative: "Piotrkowie Trybunalskim", genitive: "Piotrkowa Trybunalskiego" },
  plock: { locative: "Płocku", genitive: "Płocka" },
  police: { locative: "Policach", genitive: "Polic" },
  poznan: { locative: "Poznaniu", genitive: "Poznania" },
  pruszkow: { locative: "Pruszkowie", genitive: "Pruszkowa" },
  przemysl: { locative: "Przemyślu", genitive: "Przemyśla" },
  pultusk: { locative: "Pułtusku", genitive: "Pułtuska" },
  pulawy: { locative: "Puławach", genitive: "Puław" },
  raciborz: { locative: "Raciborzu", genitive: "Raciborza" },
  radom: { locative: "Radomiu", genitive: "Radomia" },
  radomsko: { locative: "Radomsku", genitive: "Radomska" },
  rawicz: { locative: "Rawiczu", genitive: "Rawicza" },
  rybnik: { locative: "Rybniku", genitive: "Rybnika" },
  "ruda-slaska": { locative: "Rudzie Śląskiej", genitive: "Rudy Śląskiej" },
  rudaslaska: { locative: "Rudzie Śląskiej", genitive: "Rudy Śląskiej" },
  rzeszow: { locative: "Rzeszowie", genitive: "Rzeszowa" },
  sanok: { locative: "Sanoku", genitive: "Sanoka" },
  siedlce: { locative: "Siedlcach", genitive: "Siedlec" },
  "siemianowice-slaskie": { locative: "Siemianowicach Śląskich", genitive: "Siemianowic Śląskich" },
  "skarzysko-kamienna": { locative: "Skarżysku-Kamiennej", genitive: "Skarżyska-Kamiennej" },
  skawina: { locative: "Skawinie", genitive: "Skawiny" },
  skierniewice: { locative: "Skierniewicach", genitive: "Skierniewic" },
  slupsk: { locative: "Słupsku", genitive: "Słupska" },
  sopot: { locative: "Sopocie", genitive: "Sopotu" },
  sosnowiec: { locative: "Sosnowcu", genitive: "Sosnowca" },
  stargard: { locative: "Stargardzie", genitive: "Stargardu" },
  starachowice: { locative: "Starachowicach", genitive: "Starachowic" },
  "stalowa-wola": { locative: "Stalowej Woli", genitive: "Stalowej Woli" },
  stalowawola: { locative: "Stalowej Woli", genitive: "Stalowej Woli" },
  suwalki: { locative: "Suwałkach", genitive: "Suwałk" },
  swarzedz: { locative: "Swarzędzu", genitive: "Swarzędza" },
  swidnica: { locative: "Świdnicy", genitive: "Świdnicy" },
  swietochlowice: { locative: "Świętochłowicach", genitive: "Świętochłowic" },
  swinoujscie: { locative: "Świnoujściu", genitive: "Świnoujścia" },
  szczecin: { locative: "Szczecinie", genitive: "Szczecina" },
  szczecinek: { locative: "Szczecinku", genitive: "Szczecinka" },
  tarnow: { locative: "Tarnowie", genitive: "Tarnowa" },
  "tarnowskie-gory": { locative: "Tarnowskich Górach", genitive: "Tarnowskich Gór" },
  "tomaszow-mazowiecki": { locative: "Tomaszowie Mazowieckim", genitive: "Tomaszowa Mazowieckiego" },
  tomaszowmazowiecki: { locative: "Tomaszowie Mazowieckim", genitive: "Tomaszowa Mazowieckiego" },
  torun: { locative: "Toruniu", genitive: "Torunia" },
  tychy: { locative: "Tychach", genitive: "Tych" },
  wabrzezno: { locative: "Wąbrzeźnie", genitive: "Wąbrzeźna" },
  wadowice: { locative: "Wadowicach", genitive: "Wadowic" },
  walbrzych: { locative: "Wałbrzychu", genitive: "Wałbrzycha" },
  warszawa: { locative: "Warszawie", genitive: "Warszawy" },
  wloclawek: { locative: "Włocławku", genitive: "Włocławka" },
  wroclaw: { locative: "Wrocławiu", genitive: "Wrocławia" },
  wrzesnia: { locative: "Wrześni", genitive: "Wrześni" },
  zabrze: { locative: "Zabrzu", genitive: "Zabrza" },
  zakopane: { locative: "Zakopanem", genitive: "Zakopanego" },
  zamosc: { locative: "Zamościu", genitive: "Zamościa" },
  zawiercie: { locative: "Zawierciu", genitive: "Zawiercia" },
  zgierz: { locative: "Zgierzu", genitive: "Zgierza" },
  zgorzelec: { locative: "Zgorzelcu", genitive: "Zgorzelca" },
  "zielona-gora": { locative: "Zielonej Górze", genitive: "Zielonej Góry" },
  zielonagora: { locative: "Zielonej Górze", genitive: "Zielonej Góry" },
  zory: { locative: "Żorach", genitive: "Żor" },
  zyrardow: { locative: "Żyrardowie", genitive: "Żyrardowa" },
};
